services:
  mariadb:
    image: mariadb:latest
    container_name: mate-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: danjam
      MYSQL_USER: danjam
      MYSQL_PASSWORD: danjam
    ports:
      - "3309:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mate-phpmyadmin
    environment:
      PMA_HOST: mariadb   # 기본적으로 mariadb에 연결
      PMA_HOSTS: mariadb # mariadb
      PMA_USER: danjam
      PMA_PASSWORD: danjam
      MYSQL_ROOT_PASSWORD: 1234  # MariaDB root 비밀번호
    ports:
      - "9009:80"  # phpMyAdmin에 접속하는 포트 (브라우저에서 http://localhost:8080 사용)
    depends_on:
      - mariadb
  redis:
    image: redis:alpine
    container_name: mate-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "danjam" ]
volumes:
  mariadb_data:
  redis_data: