server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: ${EUREKA_REGISTER_WITH_EUREKA}
    fetch-registry: ${EUREKA_FETCH_REGISTRY}
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE}

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        #로그인 필요없는 요청(토큰 검증 필터 x)
        - id: user-service-signup
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/signup
            - Method=POST
        - id: user-service-login
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/login
            - Method=POST
        - id: user-service-logout
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/logout
            - Method=POST

        #로그인 필요한 요청(토큰 검증 필터 o)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - name: AuthPermissionFilter
        - id: mate-service
          uri: lb://mate-service
          predicates:
            - Path=/mate-service/**
          filters:
            - name: AuthPermissionFilter
  jwt:
    secret: ${SPRING_JWT_SECRET}
