server:
  port: ${SERVER_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        #로그인 필요없는 요청(토큰 검증 필터 x)
        - id: user-service-signup
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/signup
            - Method=POST
        - id: user-service-login
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/login
            - Method=POST
        - id: user-service-logout
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/logout
            - Method=POST
        - id: user-service-token-reissue
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/token/reissue
            - Method=POST

        #로그인 필요한 요청(토큰 검증 필터 o)
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/**
          filters:
            - name: AuthPermissionFilter
        - id: mate-service
          uri: lb://mate-service
          predicates:
            - Path=/mate-service/api/**
          filters:
            - name: AuthPermissionFilter
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/schedule-service/api/**
          filters:
            - name: AuthPermissionFilter

        # swagger-ui 요청 매핑
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - StripPrefix=1
  jwt:
    secret: ${SPRING_JWT_SECRET}

springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
